### ISSUE TITLE
discovery.py needs py >= 3.8

### ISSUE THREAD

**Issue by max3-2** [John-Hennig/MPh#23]
Running `discovery.py` (or any module that depends) with Windows will lead to 

```python
Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import mph
>>> s = mph.Server()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nnn\.pyenvs\t\lib\site-packages\mph\server.py", line 83, in __init__
    backend = discovery.backend(version)
  File "C:\Users\nnn\.pyenvs\t\lib\site-packages\mph\discovery.py", line 403, in backend
    backends = search_system()
  File "C:\Users\nnn\.pyenvs\t\lib\site-packages\mph\discovery.py", line 380, in search_system
    return search_Windows()
  File "C:\Users\nnn\.pyenvs\t\lib\site-packages\mph\discovery.py", line 141, in search_Windows
    creationflags=0x08000000)
  File "C:\Users\nnn\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\nnn\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\nnn\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Users\nnn\AppData\Local\Programs\Python\Python37\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

which seems to be the issue here: https://bugs.python.org/issue33617

The exception is gone with updating python. However, the requirements state `3.6` which is not valid.

1) `str()` cast the `Path()`?
2) update requirements?

Best

**Comment by John-Hennig** [comment]
Good catch. I do test with Python 3.6, but on Linux. On Windows, I have 3.9. I don't quite see why there would be a difference between the platforms at this point in the code, but will look into this. There is no good reason (yet) to drop support for the older Python. So apparently there *are* some parts of the standard library that don't fully support Path-like objects. I'll run the tests with 3.6 and figure out a work-around.
