### ISSUE TITLE
OSError: [WinError 193] %1 is not a valid Win32 application 

### ISSUE THREAD

**Issue by Eify666666** [John-Hennig/MPh#5]
when I use mph, it happens.

Traceback (most recent call last):
  File "F:/python project/test_mph/test_model.py", line 268, in <module>
    setup_module()
  File "F:/python project/test_mph/test_model.py", line 27, in setup_module
    client = mph.Client()
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\site-packages\mph\client.py", line 85, in __init__
    main = backend.folder(version)
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\site-packages\mph\backend.py", line 214, in folder
    last = list(versions().keys())[-1]
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\site-packages\mph\backend.py", line 125, in versions
    process = run(f'{path} --version', stdout=PIPE, creationflags=flags)
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Eify\.conda\envs\pytorch160\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application 

how can i do for this?

python 3.7

**Comment by Eify666666** [comment]
I find the reasons and solutions.
There is a **space** in my path of comsol.
When i retool the comsol, it works.

Here is the same question and solution.
[](https://teratail.com/questions/127811)

**Comment by John-Hennig** [comment]
I could not reproduce this, even with spaces in the path to the Comsol installation. But I fixed a related issue in the latest release, 0.7.6.
